import { useEffect, useMemo, useState } from 'react';
import { useLocalMemory } from '@/hooks/useLocalMemory';
import { backupToGoogleDrive, connectGoogleDrive, createGmailDraft, createGoogleCalendarEvent, createGoogleSheet, disconnectGoogleDrive, exportTasksToGoogleSheet, getGoogleClientId, getStoredDriveToken, restoreFromGoogleDrive, setGoogleClientId, syncTasksToGoogleCalendar } from '@/lib/googleDriveCloud';

function today() { return new Date().toISOString().slice(0, 10); }

export default function SystemHubPage() {
  const memory = useLocalMemory();
  const [clientId, setClientIdState] = useState(getGoogleClientId());
  const [googleConnected, setGoogleConnected] = useState(Boolean(getStoredDriveToken()));
  const [busy, setBusy] = useState(false);
  const [message, setMessage] = useState('');
  const [aiStatus, setAiStatus] = useState<{ geminiConfigured?: boolean; openaiConfigured?: boolean; model?: string } | null>(null);
  const datedTasks = useMemo(() => memory.tasks.filter((task) => task.dueDate && task.status !== 'done'), [memory.tasks]);
  const urgentTasks = useMemo(() => memory.tasks.filter((task) => task.status !== 'done' && (task.priority === 'urgent' || task.priority === 'high')), [memory.tasks]);
  const geminiReady = Boolean(aiStatus?.geminiConfigured || aiStatus?.openaiConfigured);
  useEffect(() => { fetch('/api/agents/status').then((res) => res.json()).then(setAiStatus).catch(() => setAiStatus(null)); }, []);
  async function run(label: string, action: () => Promise<unknown>) { try { setBusy(true); setMessage(`جاري تنفيذ: ${label}`); await action(); setGoogleConnected(Boolean(getStoredDriveToken())); await memory.refresh(); setMessage(`تم: ${label}`); } catch (error) { setMessage(error instanceof Error ? error.message : 'حدث خطأ غير معروف'); } finally { setBusy(false); } }

  return (
    <main className="system-shell" dir="rtl"><style>{styles}</style>
      <header className="hero-card"><a className="back" href="/">← الرجوع للرئيسية</a><a className="agents-link" href="/agents">الوكلاء التنفيذيون</a><span className="eyebrow">Focus Flow Operating System</span><h1>مركز النظام والخدمات</h1><p>مركز تشغيل Gemini وخدمات Google والنسخ الاحتياطي والمزامنة.</p></header>
      <section className="status-grid"><div className="status-card"><b>Gemini</b><strong>{geminiReady ? 'متصل' : 'غير مفعل'}</strong><small>{aiStatus?.model || 'أضف GEMINI_API_KEY في Vercel'}</small></div><div className="status-card"><b>Google</b><strong>{googleConnected ? 'متصل' : 'غير متصل'}</strong><small>Drive + Calendar + Gmail + Sheets</small></div><div className="status-card"><b>مهام مؤرخة</b><strong>{datedTasks.length}</strong><small>جاهزة للمزامنة مع التقويم</small></div><div className="status-card"><b>أولوية عالية</b><strong>{urgentTasks.length}</strong><small>تحتاج متابعة اليوم</small></div></section>
      <section className="panel"><div className="section-title"><h2>Google Cloud Integration</h2><span>Drive + Calendar + Gmail + Sheets</span></div><p>هذا الربط يستخدم Google OAuth Client ID من جهة الواجهة. أضف Client ID وفعل الخدمات المطلوبة.</p><label>Google OAuth Client ID<input value={clientId} onChange={(event) => setClientIdState(event.target.value)} placeholder="ضع Google OAuth Client ID هنا" /></label><div className="actions"><button disabled={busy} onClick={() => { setGoogleClientId(clientId); setMessage('تم حفظ Google Client ID'); }}>حفظ Client ID</button><button disabled={busy} onClick={() => run('ربط Google', connectGoogleDrive)}>ربط Google</button><button disabled={busy} onClick={() => run('نسخ احتياطي إلى Drive', backupToGoogleDrive)}>نسخ Drive</button><button disabled={busy} onClick={() => confirm('سيتم استبدال البيانات المحلية بآخر نسخة محفوظة. متأكد؟') && run('استعادة من Drive', restoreFromGoogleDrive)}>استعادة Drive</button><button className="ghost" onClick={() => { disconnectGoogleDrive(); setGoogleConnected(false); setMessage('تم فصل Google'); }}>فصل Google</button></div>{message && <div className="message">{message}</div>}</section>
      <section className="panel"><div className="section-title"><h2>المهام والتقويم</h2><span>Google Calendar</span></div><div className="actions"><button disabled={busy || !datedTasks.length} onClick={() => run('مزامنة كل المهام المؤرخة مع Google Calendar', () => syncTasksToGoogleCalendar(memory.tasks))}>مزامنة التقويم</button><button disabled={busy} onClick={() => run('تصدير المهام إلى Google Sheets', () => exportTasksToGoogleSheet(memory.tasks))}>تصدير Sheets</button><button disabled={busy} onClick={() => run('اختبار مسودة Gmail', () => createGmailDraft({ subject: 'اختبار Focus Flow', body: 'هذه مسودة تجريبية من Focus Flow.' }))}>اختبار Gmail Draft</button><button disabled={busy} onClick={() => run('إنشاء Google Sheet تجريبي', () => createGoogleSheet({ title: `Focus Flow Test ${today()}`, columns: ['البند', 'الحالة', 'التاريخ'], rows: [['اختبار الربط', 'ناجح عند عدم ظهور خطأ', today()], ['المصدر', 'System Hub', today()]] }))}>إنشاء Sheet تجريبي</button></div><div className="task-list">{datedTasks.slice(0, 12).map((task) => <div className="task-row" key={task.id}><div><b>{task.title}</b><small>{task.dueDate || today()} · {task.dueTime || '09:00'} · {task.priority}</small></div><button disabled={busy} onClick={() => run(`إضافة ${task.title} إلى التقويم`, () => createGoogleCalendarEvent(task))}>أضف للتقويم</button></div>)}{!datedTasks.length && <small>لا توجد مهام مؤرخة. أضف تاريخًا للمهمة أولًا.</small>}</div></section>
      <section className="panel setup"><h2>ما الذي يحتاج إعداد منك؟</h2><ul><li>في Vercel أضف GEMINI_API_KEY ثم Redeploy.</li><li>في Google Cloud فعّل Drive API و Calendar API و Gmail API و Sheets API.</li><li>أنشئ OAuth Client ID للويب وأضف رابط Vercel ضمن Authorized JavaScript origins.</li><li>ضع Client ID في هذا المركز واضغط ربط Google.</li></ul></section>
    </main>
  );
}

const styles = `:root{color-scheme:dark;font-family:Cairo,-apple-system,BlinkMacSystemFont,"SF Pro Display",Inter,system-ui,sans-serif;background:#050816}*{box-sizing:border-box}body{margin:0;background:radial-gradient(circle at 20% 0%,#1d2b6b 0,#080b18 42%,#04050b 100%);color:#f8fafc}.system-shell{max-width:1100px;margin:auto;padding:20px 16px 80px}.hero-card,.panel,.status-card{border:1px solid rgba(255,255,255,.14);background:linear-gradient(145deg,rgba(255,255,255,.13),rgba(255,255,255,.04));border-radius:34px;box-shadow:0 24px 80px rgba(0,0,0,.34),inset 0 1px 0 rgba(255,255,255,.08);backdrop-filter:blur(18px)}.hero-card{padding:28px;text-align:center;display:grid;gap:12px;position:relative}.back,.agents-link{color:#bfdbfe;text-decoration:none}.back{justify-self:start}.agents-link{position:absolute;left:28px;top:28px}.eyebrow{color:#67e8f9;letter-spacing:.24em;text-transform:uppercase;font-size:12px}.hero-card h1{font-size:clamp(42px,10vw,78px);letter-spacing:-.05em;margin:0}.hero-card p{max-width:780px;margin:auto;color:#cbd5e1;line-height:1.8}.status-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:14px;margin:18px 0}.status-card{padding:18px;display:grid;gap:10px}.status-card b,.section-title span,.task-row small,.panel p{color:#cbd5e1}.status-card strong{font-size:34px}.panel{padding:22px;margin-top:16px}.section-title{display:flex;align-items:center;justify-content:space-between;gap:12px;margin-bottom:14px}.section-title h2{margin:0}label{display:grid;gap:8px;color:#dbeafe}input{width:100%;border:1px solid rgba(255,255,255,.14);border-radius:20px;background:rgba(15,23,42,.72);color:#fff;padding:15px 16px;outline:none;font:inherit}.actions{display:flex;gap:10px;flex-wrap:wrap;margin-top:14px}.actions button,.task-row button{border:0;min-height:48px;border-radius:18px;padding:0 16px;color:#fff;font-weight:950;background:linear-gradient(135deg,#06b6d4,#2563eb,#7c3aed)}.actions button:disabled,.task-row button:disabled{opacity:.55}.ghost{background:rgba(255,255,255,.1)!important}.message{margin-top:14px;border-radius:18px;background:rgba(34,197,94,.14);color:#bbf7d0;padding:14px}.task-list{display:grid;gap:10px;margin-top:14px}.task-row{display:flex;justify-content:space-between;align-items:center;gap:12px;border:1px solid rgba(255,255,255,.1);background:rgba(15,23,42,.62);padding:14px;border-radius:20px}.task-row div{display:grid;gap:4px}.setup li{margin-bottom:8px;color:#dbeafe;line-height:1.7}@media(max-width:780px){.system-shell{padding:14px 12px 70px}.status-grid{grid-template-columns:repeat(2,minmax(0,1fr))}.task-row{align-items:stretch;flex-direction:column}.task-row button{width:100%}.actions button{flex:1;min-width:calc(50% - 8px)}.agents-link{position:static;justify-self:start}}`;